development: &development
  small_blog_post_template: "[{\"type\":\"DayOfWeek\",\"schedule\":[2,4],\"count\":1}]"
  small_tweet_template: "[{\"type\":\"DayOfWeek\",\"schedule\":[1,2,3,4,5],\"count\":5},{\"type\":\"DayOfWeek\",\"schedule\":[0,6],\"count\":2}]"
  
test:
  <<: *development

production:
  <<: *development